Check Version: true
Messages:
  no-permissions: '&cYou do not have the permission required to do this action!'
  chat-disabled: '&c%CHAT_NAME% is currently disabled. Please try again later.'
  reload: '&aVIP+ Chat config has been reloaded!'
  toggle: '&7You have currently set &9%CHAT_NAME% &7to state &9%STATE%.'
  error: '&cThere appears to be a error occurring with this action.'
  info-player-not-found: '&9%PLAYER% &7was not found.'
  info-player-layout: '&6--- &9Player Info&7: %PLAYER% &6---%NL%%ITEMS%'
  info-player-items: '&9%INFO_TITLE%&7: &6%INFO_DETAILS%%NL%'
  ignore: '&7You have set &9%CHAT_NAME% &7to be &9%STATUS%&7.'
  ignore-fail: '&cYou did not enter a proper chat name.'
  ignore-already: '&7You appear to have already set your self to &9%STATUS% &7for
    &9%CHAT_NAME%&7.'
  ignore-not-found: '&7Your name was not found to &9%STATUS% %CHAT_NAME%&7.'
  ignored-layout: '&6--- &9Ignored &7(&c%COUNT%&7)&6 ---%NL%%ITEMS%&6Page &7(&9%PL#%&7/&9%PH#%&7)
    &6/vpc ignored {chat} {#}'
  ignored-items: '&6%#%. &7%PLAYER_NAME% &9-&7 %PLAYER_UUID%%NL%'
  blacklisted-layout: '&6--- &9Blacklisted &7(&c%COUNT%&7)&6 ---%NL%%ITEMS%&6Page
    &7(&9%PL#%&7/&9%PH#%&7) &6/vpc blacklisted {#}'
  blacklisted-items: '&6%#%. &7%PLAYER_NAME% &9-&7 %PLAYER_UUID%%NL%'
  ignore-blacklist: '&cYou were blacklisted from ignoring staff chat'
  ignore-disabled: '&c%CHAT_NAME% has been disabled the use of ignoring chat.'
  blacklisted: '&7You have blacklisted &9%PLAYER%&7. This user may no longer ignore
    any chats.'
  remove-blacklisted: '&7You have removed &9%PLAYER%&7 from the blacklist. This user
    may now ignore any chats.'
  force-unignore: '&7You have forced &9%PLAYER% &7to unignore chat &9%CHAT_NAME%'
  colors: '%COLOR%:%STATE%%NL%'
  focus-mode-toggle: '&7You have %STATE% &7focus mode for chat &9%CHAT_NAME%.'
  focused: '&7You are currently focused on chat &9%CHAT_NAME%'
  pstatus-layout: '&6--- &9%PLAYER_NAME% &7Status &6---%NL%%IGNORED_START%&6Ignored
    List:%NL%%IGNORED_ITEMS%%IGNORED_END%%BOTH_START%%NL%%BOTH_END%%BLACKLISTED_START%&6Blacklisted:
    %STATUS_BLACKLISTED%%BLACKLISTED_END%'
  pstatus-ignored-items: '%CHAT_TAG%&f: %STATUS%%NL%'
  pstatus-invalid-chat: '&cYou have entered a invalid chat.'
  pstatus-syntax: '&cYou have entered a invalid syntax for this command &6/vpc pstatus
    | Optional 1: {blacklisted/ignored} | Optional 2: {chat}'
  ignore-list: '&7Ignored &8(&9%CHAT_NAME%&8): &7%LIST%'
  blacklisted-list: '&7Blacklisted &8(&9%COUNT%&8): &7%LIST%'
  player-ignore: '&7You have set &9%IGNORE_PLAYER% &7to be %STATUS%&7.'
  player-ignore-syntax: '&cThat is a invalid usage of that command. Please try again: &6/vpc ignoreplayer {player/clear} | Optional: {+,add,rem,remove,del,delete,clear}'
  player-ignore-list-layout: '&6--- &9Player Ignore List &7(&c%COUNT%&7)&6 ---%NL%%ITEMS%&6Page &7(&9%PL#%&7/&9%PH#%&7) &6/vpc listplayers | Optional: {#}'
  player-ignore-list-items: '&6%#%. &7%PLAYER_NAME% &9-&7 %PLAYER_UUID%%NL%'
  player-ignore-list-syntax: '&cThat is a invalid usage of that command. Please try again: &6/vpc listplayers | Optional: {#}'
  antiswear-toggle: '&7You have %STATUS% &7Anti Swear for %CHAT_TAG%&7.'
  antiswear-chat-syntax: '&cIt appears you did not enter a proper chat for this command. Please try again: &6%COMMAND%'
  antiswear-syntax: '&cIt appears you did not enter a proper command. Please try again: &6%COMMAND%'
  antiswear-word-remove: '&7The word &9%WORD% &7was %STATE% &7from %CHAT_TAG%''s &7swear list.'
  antiswear-word-add: '&7The word &9%WORD% &7has been added to %CHAT_TAG%''s swear list.'
  antiswear-word-clear: '&7You have cleared the swear dictionary for %CHAT_TAG%&7.'
  antiswear-banned: '&cIt appears you have used a word that is not allowed in %CHAT_TAG%&c'
  antiswear-already: '&cIt appears the dictionary already contains &9%WORD% &7for swear list %CHAT_TAG%&c.'
  antiswear-list-layout: '&6--- &9Swear Dictionary &f[%CHAT_TAG%&f] &7(&c%COUNT%&7)&6 ---%NL%%ITEMS%&6Page &7(&9%PL#%&7/&9%PH#%&7) &6/vpc swear list {#}'
  antiswear-list-items: '&6%#%. &7%WORD% &9-&7 %REPLACEMENT%%NL%'
Other:
  focus:
    saved: true
    location: \files\focus.yml
  blacklisted-length: 10
  ignored-length: 10
  player-ignore-length: 10
  antiswear-list-server-length: 15
  antiswear-list-player-length: 15
  blacklist: ''
  Blacklist-Settings:
    can-ignore-chats:
      enabled: true
      specified-chats:
      - none
    can-talk-in-chats:
      enabled: false
      specified-chats:
      - none
    can-view-chats:
      enabled: false
      specified-chats:
      - none
  broadcast: true